#!/bin/bash

# Usage:
# generate-deployment-descriptor.sh DEPLOYMENT_TARGET DEPLOYMENT_TARGET_MANIFESTS_PATH APPLICATION OUTPUT_FILE TEMPLATE_FILE

export DEPLOYMENT_TARGET=$1
export DEPLOYMENT_TARGET_MANIFESTS_PATH=$2
export APPLICATION=$3
OUTPUT_FILE=$4
TEMPLATE_FILE=$5

echo $DEPLOYMENT_TARGET
echo $DEPLOYMENT_TARGET_MANIFESTS_PATH
echo $APPLICATION
echo $OUTPUT_FILE
echo $TEMPLATE_FILE


set -eo pipefail

envsubst <"$TEMPLATE_FILE" > "$OUTPUT_FILE"



